from dotenv import load_dotenv, find_dotenv
import os
load_dotenv(find_dotenv(), override=True)

AIRTABLE_TOKEN=os.environ['AIRTABLE_TOKEN']
AIRTABLE_BASE_ID=os.environ['AIRTABLE_BASE_ID']
AIRTABLE_TABLE_ID=os.environ['AIRTABLE_TABLE_ID']
AIRTABLE_BUILDBOUNTY_TOKEN=os.environ['AIRTABLE_BUILDBOUNTY_TOKEN']
AIRTABLE_BUILDBOUNTY_BASE_ID=os.environ['AIRTABLE_BUILDBOUNTY_BASE_ID']
AIRTABLE_BUILDBOUNTY_MEMBERS_TABLE_ID=os.environ['AIRTABLE_BUILDBOUNTY_MEMBERS_TABLE_ID']
AIRTABLE_BUILDBOUNTY_MEMBERSGENAIVERSION_TABLE_ID=os.environ['AIRTABLE_BUILDBOUNTY_MEMBERSGENAIVERSION_TABLE_ID']
AIRTABLE_BUILDBOUNTY_BUILDUPDATES_TABLE_ID=os.environ['AIRTABLE_BUILDBOUNTY_BUILDUPDATES_TABLE_ID']

INDEX_NAMES={
    AIRTABLE_TABLE_ID : 'Members',
    AIRTABLE_BUILDBOUNTY_MEMBERS_TABLE_ID : 'BuildBountyMembers',
    AIRTABLE_BUILDBOUNTY_MEMBERSGENAIVERSION_TABLE_ID : 'BuildBountyMembersGenAI',
    AIRTABLE_BUILDBOUNTY_BUILDUPDATES_TABLE_ID : 'BuildBounty'
}

AIRTABLE_CONFIG={
    'Members' : {
        'TOKEN': AIRTABLE_TOKEN,
        'BASE': AIRTABLE_BASE_ID,
        'TABLE': AIRTABLE_TABLE_ID,
    },
    'BuildBountyMembers':{
        'TOKEN': AIRTABLE_BUILDBOUNTY_TOKEN,
        'BASE': AIRTABLE_BUILDBOUNTY_BASE_ID,
        'TABLE': AIRTABLE_BUILDBOUNTY_MEMBERS_TABLE_ID
    },
    'BuildBountyMembersGenAI':{
        'TOKEN': AIRTABLE_BUILDBOUNTY_TOKEN,
        'BASE': AIRTABLE_BUILDBOUNTY_BASE_ID,
        'TABLE': AIRTABLE_BUILDBOUNTY_MEMBERSGENAIVERSION_TABLE_ID
    },
    'BuildBountyBuildUpdates':{
        'TOKEN': AIRTABLE_BUILDBOUNTY_TOKEN,
        'BASE': AIRTABLE_BUILDBOUNTY_BASE_ID,
        'TABLE': AIRTABLE_BUILDBOUNTY_BUILDUPDATES_TABLE_ID
    }
}